### ISSUE TITLE
Hang if you try to flash the firmware with no Arduino attached.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#200] opened 2017-06-17 17:41 UTC
0.9 RC4
Mac or Windows

Launch the AYAB software, but do not plug in the USB to the hardware.

Tools menu - Load AYAB firmware
select anything: 910, Uno, 0.8
Click Flash.
Nothing is happening, but you can't close the firmware window.

Expected, either:
 - the Flash button should not be live if it hasn't found an Arduino
 - it should check the port first and show an error message.
I prefer the second one.

**Comment by oskay** [comment] 2017-06-17 23:07
Confirmed (Mac).

**Comment by chris007de** [comment] 2017-06-19 16:31
So I guess we want to have some kind of Arduino detection.
Here are some examples:
- https://stackoverflow.com/questions/24214643/python-to-automatically-select-serial-ports-for-arduino
- https://arduino-er.blogspot.de/2015/04/python-auto-detect-arduino-connect.html

Let's see how reliable that works, we should avoid to lock out users with exotic Arduino clones.

**Comment by oskay** [comment] 2017-06-19 17:04
Without adding a library, would it be possible to simply detect that the selected serial port is "sensible" before attempting to flash?

**Comment by chris007de** [comment] 2017-06-19 17:57
We are already importing "serial" to do the actual communication, so this would not be a big deal.
Detection based on sensible portnames would a very basic approach, but might also yield false positives (e.g. checking for /dev/ttyACM* or /dev/ttyUSB*).
I'll have a look into it and propose a solution.

**Comment by chris007de** [comment] 2020-07-24 20:35
Still occurs. If I try `Flash` on a serial port where no Arduino is connected, avrdude is just stuck forever.

**Comment by t0mpr1c3** [comment] 2020-07-24 21:20
Since we poll the subprocess for output, we should be able to signal a fail if the process times out. 10 seconds should be enough, right?

**Comment by chris007de** [comment] 2020-07-25 09:06
> Since we poll the subprocess for output, we should be able to signal a fail if the process times out. 10 seconds should be enough, right?

Yes, 10 secs should be a reasonable timeout.

**Comment by dl1com** [comment] 2023-05-14 13:39
Trying to flash the firmware without having an arduino attached shows error box "Error flashing firmware".
Tested with test230514 (debian).

Closing...

**Closed by dl1com** 2023-05-14 13:39 UTC
Labels: bug, ready - please test
