### ISSUE TITLE
Problem at the start of AYAB

### ISSUE THREAD

**Issue by Francoize** [AllYarnsAreBeautiful/ayab-desktop#267] opened 2018-10-04 10:56 UTC
Hello,

I've got a problem launching AYAB. The window open and then close instantly so I don't have the time to read what happens.

Here is the install .log

Cloning into '/Users/francoiselesage/.pyenv'...
Cloning into '/Users/francoiselesage/.pyenv/plugins/pyenv-doctor'...
Cloning into '/Users/francoiselesage/.pyenv/plugins/pyenv-installer'...
Cloning into '/Users/francoiselesage/.pyenv/plugins/pyenv-update'...
Cloning into '/Users/francoiselesage/.pyenv/plugins/pyenv-virtualenv'...
Cloning into '/Users/francoiselesage/.pyenv/plugins/pyenv-which-ext'...

WARNING: seems you still have not added 'pyenv' to the load path.

# Load pyenv automatically by adding
# the following to ~/.bashrc:

export PATH="/Users/francoiselesage/.pyenv/bin:$PATH"
eval "$(pyenv init -)"
eval "$(pyenv virtualenv-init -)"

Can somebody help me?
I don't have any knowledge in programming so it's a bit harsh for me to understand a thing.

Thank very much in advance.

**Comment by oskay** [comment] 2018-10-04 16:42
Can you please say which
* operating system and version you are using
* version of AYAB you are using

**Comment by Francoize** [comment] 2018-10-05 08:51
The computer runs with MacosX Mojave (10.14)
And AYAB is the v0.9 downloadable [here](http://ayab-knitting.com/ayab-software/)

Thank you

**Comment by oskay** [comment] 2018-10-05 09:59
I can confirm that this is not a general problem with MacOS 10.14 +AYAB 0.9; this combination seems to launch just fine (at least on my computer here). 

So the issue is likely an installation or configuration problem (as opposed to a conflict with 10.14, for example).  @chris007de Any ideas?

**Comment by hamsterwoede** [comment] 2018-10-05 10:15
I can confirm the problem with macOS 10.13.6. It seems to be related to the python installation. I did manage to get a screenshot before it closed by using screencapture. FIY I have had several python versions installed in the past, so my case might just refer to an older installation that I haven't cleaned up properly.
![image](https://user-images.githubusercontent.com/13483632/46529715-c9705800-c897-11e8-93ff-5221fe3fa6a1.png)

**Comment by hamsterwoede** [comment] 2018-10-05 10:30
Reinstalling xcode command line tools solved my problem.

**Comment by Francoize** [comment] 2018-10-05 10:38
I've already reinstall Xcode command line tools and update them and it doesn't make any difference and I'm not able to take a screenshot of the AYAB window because it close itself too quickly.

**Comment by hamsterwoede** [comment] 2018-10-05 11:04
I used quicktime player to do a screen capture, so I could hopefully find the right frame. It took me four tries, in which I had to delete the app, and  copy it again from the image.

**Comment by Francoize** [comment] 2018-10-05 13:15
I'm on python 3.7

**Comment by oskay** [comment] 2018-10-05 16:04
My copy of AYAB appears to be using python 3.5 frameworks, but my system python version is 3.6. Thus far, that doesn't seem like an issue.

@Francoize: 
Did you try following the instructions from the installer ("Load pyenv automatically by adding the following to ~/.bashrc:")? 
(And if you did not, would you like assistance with that part?)

**Comment by hamsterwoede** [comment] 2018-10-08 12:29
I tried python 3.7, and I have no problems. The problem might be the installation of pyenv in that case. @Francoize I would take @oskay up on his offer to assist you with setting that up. I did mine using homebrew, but that might be a bit overkill for somebody who's not using it for programming.

**Comment by Francoize** [comment] 2018-10-08 15:19
@oskay I wasn't with my computer this week-end and don't really understand how to Load pyenv automatically by adding the following to ~/.bashrc: 

If you can assist me with that it would be really helpful, Thank you.

**Comment by oskay** [comment] 2018-10-08 19:32
- Please open up TextEdit (Applications > TextEdit).

- Select File > Open... ( or command-o / ⌘-o)

- Navigate to your home folder. 
Mine is /drivename/Users/oskay/, but if you're not sure, try command-shift-h (⌘-shift-h) to switch to your home directory.

- Enable viewing of invisible files. You can do this with a special command-key sequence: ⌘-shift->,
which is the same as command-shift-period.

- Once you've done that, you should see a number of additional "invisible" files in your home folder listing-- files that start with a "." so that they don't normally show up in directory listings.

- From the list, select .bashrc and open it. The file likely contains a few lines of code. After those lines, copy and paste the following three lines (per your instructions above):
`export PATH="/Users/francoiselesage/.pyenv/bin:$PATH"`
`eval "$(pyenv init -)"`
`eval "$(pyenv virtualenv-init -)"`

- Save and close .bashrc

If you have trouble at any step, please indicate clearly what went wrong, and I'll do my best to help.

**Comment by Francoize** [comment] 2018-10-09 06:39
I don't find .bashrc this is with I've got.
![capture d ecran 2018-10-09 a 08 37 50](https://user-images.githubusercontent.com/43848026/46650999-d1354280-cb9e-11e8-8f45-3757a8eead8c.png)

**Comment by oskay** [comment] 2018-10-09 09:33
*If* that is your home directory -- I can't tell from the screenshot -- then you can create a new .bashrc file. 

- Create a new file in TextEdit (File > New)
- Change the file to be plain text mode (Format > Make plain text)
- Paste the three lines that are supposed to be in the file
- Save the file as `.bashrc` in your home directory.

**Comment by chris007de** [comment] 2018-10-10 15:42
We definitely have to think of another way to distribute the software on Mac. Whoever has got free resources, please check if https://github.com/AllYarnsAreBeautiful/ayab-desktop/issues/253 might help us.

**Comment by Francoize** [comment] 2018-10-10 15:53
It is my home directory, I created a .bashrc and paste the lines but AYAB continue to shut down before it has started this is what I've got.
![capture d ecran 2018-10-10 a 12 28 52](https://user-images.githubusercontent.com/43848026/46730452-78da6f80-cc88-11e8-8623-08f9507714c5.png)

**Comment by Francoize** [comment] 2018-10-10 15:55
I verified the installation of python, and I reinstalled it with homebrew but AYAB continue to shut down instantly.

Thank you for your time and patience.

**Comment by oskay** [comment] 2018-10-10 17:33
Is this *different* from what you had before? That is, are you still getting the message to add those lines to .bashrc?

**Comment by derchrisuk** [comment] 2018-10-11 01:11
There is a log file in `/tmp/ayab_install.log` which will be re-created after each start.
Maybe that will show some more details.

**Comment by Francoize** [comment] 2018-10-11 06:53
it's not different from before here is the .log 


pyenv: /Users/francoiselesage/.pyenv/versions/3.5.0 already exists
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 50: /Users/francoiselesage/.pyenv/shims/pip3: No such file or directory
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 51: /Users/francoiselesage/.pyenv/shims/pip3: No such file or directory
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 52: /Users/francoiselesage/.pyenv/shims/pip3: No such file or directory
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 53: /Users/francoiselesage/.pyenv/shims/pip3: No such file or directory
/Applications/AYAB-Launcher.app/Contents/Resources/script: line 58: /Users/francoiselesage/.pyenv/shims/python3: No such file or directory

**Comment by hamsterwoede** [comment] 2018-10-12 09:31
I can think of 3 different scenario's where this could still go wrong:

1. pip3 isn't installed? That doesn't quite explain the last line, so it seems unlikely. And furthermore it should be installed automatically when you installed python3. I'm just naming it because it is easiest to check.
2. Something to do with the shims/pyenv. I know that it's part of the whole virtual environment, but I really don't _really_ understand any of that stuff. 
3. We have some type of character encoding problem. It is a bit of a long shot, but if your name is spelled Françoise (with the cédille), then there is a slight chance that might throw something off somewhere. I'll test this by creating a user with special characters in it's name on my mac.

**Comment by oskay** [comment] 2018-10-12 18:06
On (1), you could try typing `pip3 --version` at the terminal -- that should confirm whether pip3 is properly installed.

**Comment by Francoize** [comment] 2018-10-15 07:33
I typed this at the terminal and this is what I've got.
AirdeFrancoise:~ francoiselesage$ pip3 --version
pip 18.0 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)

**Comment by suttlepitch** [comment] 2018-11-17 23:18
I am having immense issues trying to download the software onto my mac.  Followed this thread and did all the trouble shooting and just get this:

![screen shot 2018-11-17 at 4 15 33 pm](https://user-images.githubusercontent.com/45112184/48666715-58ba7f00-ea84-11e8-91ea-344c105a840b.png)

**Comment by suttlepitch** [comment] 2018-11-17 23:18
Also, it crashes almost immediately, took me a few times to try and catch this screenshot

**Comment by chris007de** [comment] 2018-11-17 23:22
Thanks for the report. Which macOS version are you using?

Am 18. November 2018 00:18:43 MEZ schrieb suttlepitch <notifications@github.com>:

**Comment by suttlepitch** [comment] 2018-11-17 23:23
Mac OS 10.14.1

**Comment by chris007de** [comment] 2018-11-17 23:27
Ok. MacOS version has currently pretty severe problems on newer systems.
We are working on a new version (0.95) which will solve this. Currently we are in testing phase, I expect it to be released not later than Christmas.
Sorry for the inconvenience, I hope you can switch to a Windows system in the mean time :(

Am 18. November 2018 00:23:12 MEZ schrieb suttlepitch <notifications@github.com>:

**Comment by suttlepitch** [comment] 2018-11-19 03:51
Newer systems as in what onward?  

Thanks for letting me know, will definitely be on the watch for the new release!

**Comment by Francoize** [comment] 2018-11-29 13:19
I solved the problem by installing virtual box and ubuntu on it, it works this way. I'm happy to know that you are working on a new Mac version.

**Closed** 2018-11-29 13:19 UTC
Labels: Mac
