### ISSUE TITLE
Crashes on Windows 10 while changing settings.

### ISSUE THREAD

**Issue by Adrienne200** [AllYarnsAreBeautiful/ayab-desktop#283] opened 2019-01-10 06:08 UTC
I had it crash randomly a few times during my weekend testing. This was on Win10, though I haven't put in enough time on Mac to be sure that it doesn't happen there too. No one particular thing that seemed to cause it, it was after I had been knitting for a while and had changed pattern a couple of times, and was changing settings or after I clicked Configure, not while knitting.
[random crashes Surface RC3.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/2743851/random.crashes.Surface.RC3.txt)

**Comment by chris007de** [comment] 2019-01-11 20:55
I was not able to reproduce this so far.
Could you please provide the ayab_log.txt right after the crash occurs? Perhaps it's a certain combination of settings which leads to the crash.

**Comment by chris007de** [comment] 2019-01-28 20:15
I can't find the line in the log where the crash happens. 
All configure commands in the logfile are handled correctly are followed by knitting.
Did you store the log file right after the crash or did you do some more knitting until you copied the file and uploaded it?

**Comment by Adrienne200** [comment] 2019-01-29 08:16
I copied off the log file immediately after the crash. A mystery, we'll just have to try and collect more data.

**Comment by Adrienne200** [comment] 2019-01-30 08:51
I had something similar on Mac today. I had been opening a few different images, then clicked Configure and it quit. Copied off the current log session, and the crash log.
[AYAB log Mac Crash 0-95FC.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/2811667/AYAB.log.Mac.Crash.0-95FC.txt)
[AYAB Mac crash 0-95FC1.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/2811668/AYAB.Mac.crash.0-95FC1.txt)

**Comment by t0mpr1c3** [comment] 2020-07-23 12:05
I suggest we can close this issue because in 1.0.0 there will no longer be a Configure button in the GUI. We can raise a new issue if similar problems recur.

**Comment by chris007de** [comment] 2020-07-24 19:48
Agreed.

**Closed by chris007de** 2020-07-24 19:48 UTC
Labels: 0.95, Windows, bug
