### ISSUE TITLE
Unable to load image (linux)

### ISSUE THREAD

**Issue by oskay** [AllYarnsAreBeautiful/ayab-desktop#159] opened 2016-12-08 05:44 UTC
**Issue:**
Testing a fresh copy of AYAB 0.8 today on Ubuntu 16.04.1, I found that it was unable to load a PNG file.
<img width="482" alt="screen shot 2016-12-07 at 9 28 40 pm" src="https://cloud.githubusercontent.com/assets/1009180/20998864/97e9e5ba-bcc5-11e6-8375-5380fee69b18.png">

**Apparent solution:**
The traceback (screenshot shown above) indicated that one should use `tobytes` instead of `tostring` on line 229 of ayab.py, in `refresh_scene`.  If one makes this change on that line, AYAB is then able to load PNG files again.

**Comment by chris007de** [comment] 2016-12-08 21:04
This was caused by an API change of the Pillow library from 2.x to 3.x, where Pillow 3.x got rid of 'tostring'.
If you installed AYAB v0.8 from PyPi, the requirements.txt states "pillow>=2.5.2", which implies that 3.x is ok also, and therefore it installed Pillow 3.x and can't handle 'tostring'.
This was fixed in 137a480a8e5ec379448326b6d1fa7a45b248d04c to use a pinned pillow version 2.6.1.

But as 'tobytes' is also supported in 2.x, we'll also change 'tostring' to 'tobytes', just to be compatible to existing library installations outside a virtualenv.

**Comment by oskay** [comment] 2016-12-08 21:27
This version was installed by following the directions linked from http://ayab-knitting.com/software-and-documentation/ .

**Comment by chris007de** [comment] 2017-02-23 21:13
Tested -> fixed

**Closed by chris007de** 2017-02-23 21:13 UTC
Labels: bug, Linux, ready - please test
