### ISSUE TITLE
Vertical scroll position is forced to center when knitting very tall patterns

### ISSUE THREAD

**Issue by still-optimistic** [AllYarnsAreBeautiful/ayab-desktop#232] opened 2017-08-14 04:51 UTC
I knit a 50 x 750 pattern, so it was much taller than the window.  I had trouble with the scrolling as follows:

* I could not use a scroll gesture to scroll down to the bottom -- it jumped back to the middle as soon as scrolling stopped.
* I could drag the scroll car to the bottom... but as soon as I knit a row, the scroll position jumped back to the middle again.

Ideally, it seems like we would set the scroll position such that the current row was visible, as well as a bit of the pattern above and below it.

I'm using 0.9rc11, running it on macOS 10.12.6.

**Comment by chris007de** [comment] 2017-08-14 16:58
Duplicate of #210

**Closed by chris007de** 2017-08-14 16:58 UTC
