### ISSUE TITLE
AYAB Desktop crash on macOS when disconnecting USB while knitting

### ISSUE THREAD

**Issue by jessedonaldson** [AllYarnsAreBeautiful/ayab-desktop#228] opened 2017-08-06 05:20 UTC
I stopped knitting by disconnecting the USB cable without clicking "Cancel Knitting" first, and AYAB crashed.  Crash report attached.  
This is on macOS 10.12.6.

[AYAB Crash.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1202888/AYAB.Crash.txt)

**Comment by chris007de** [comment] 2017-08-06 10:25
duplicate of #194

**Closed by chris007de** 2017-08-06 10:25 UTC
Labels: duplicate
