### ISSUE TITLE
Start knitting on LHS or RHS

### ISSUE THREAD

**Issue by t0mpr1c3** [AllYarnsAreBeautiful/ayab-desktop#544] opened 2023-06-19 14:45 UTC
Counterpart to https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/31

Manual selection of the carriage needs a radio button on the desktop Preferences dialog, and a change to the API informing the device of the carriage selected in the reqInit (or reqStart?)message. The desktop needs to verify the carriage reported in IndState. The host also needs to inform the device (in the reqInit or reqStart message) whether it is starting on the LHS or RHS.

**Comment by jpcornil-git** [comment] 2023-06-19 16:38
Why not handle this completely in the desktop SW ?

FW could indicate to SW via IndSate msg that the left/right hall sensor has been passed in the right/left direction respectively and transition from s_init to s_ready as of today and SW, as a function of preference settings, either accept/reject by triggering a s_operate/s_init transition ?

I believe FW/API should be made as dumb/generic as possible and focus as much as possible on HW/realtime aspects.

**Comment by t0mpr1c3** [comment] 2023-06-19 16:52
> Why not handle this completely in the desktop SW ?
> 
> FW could indicate to SW via IndSate msg that the left/right hall sensor has been passed in the right/left direction respectively and transition from s_init to s_ready as of today and SW, as a function of preference settings, either accept/reject by triggering a s_operate/s_init transition ?

I think this should be possible.

**Comment by dl1com** [comment] 2023-07-02 21:37
@AllYarnsAreBeautiful/ayab-contributors do we want to solve this for 1.0?

**Comment by t0mpr1c3** [comment] 2023-07-03 03:06
Yes, because the solution impacts the API.

**Comment by t0mpr1c3** [comment] 2024-03-07 05:40
So, is the plan still to have the user select the carriage and direction and have the desktop (host) tell the device (interface) what to expect?

I suggest that the host should tell the device this information *in every line of data* because of #607.

**Comment by jpcornil-git** [comment] 2024-03-07 07:29
If carriage detection implemented in FW is solid  (detect carriage type in both directions and reset associated carriage parameters/carriage position dynamically) I don't see what issue it will solve. If you want to recover from a power down, you would have to recover carriage position as well (not trivial to guess, most effective is to pass one LHS/RHS sensor).

=> Why would you need to enforce carriage type/direction(/position) from the GUI ?

**Comment by jpcornil-git** [comment] 2024-03-07 08:35
Because of:
- the HW issue on KH910 with RHS hall sensor ?
=> It should work for K carriages (but not L nor G) [pullup should also be enabled for that pin cfr. AllYarnsAreBeautiful/ayab-firmware/issues/51)
- not solid
=> It should be fixed then :-)

**Comment by t0mpr1c3** [comment] 2024-03-07 15:33
Yes, it is my understanding that K carriage detection on both sides should be fixed in the new hardware.

What do you propose for right now?

**Comment by jpcornil-git** [comment] 2024-03-07 15:54
K carriage can be made OK on existing HW (if there is a detection from RHS sensor on KH910 then you assume it is K [can't be L and can't distinguish from G because of the missing connection).
If you want to support G as well then SW has to tell FW 'ForceG', i.e. if you detect K (RHS) or G (LHS) it is G and you need a 'Force G' radio button to set that in the UI

**Comment by t0mpr1c3** [comment] 2024-03-07 15:59
Either way we need to change the API.

**Comment by jpcornil-git** [comment] 2024-03-07 16:06
If you want to add support for G carriage start from RHS on KH910 on existing HW yes (only use case I believe)

**Comment by t0mpr1c3** [comment] 2024-03-07 16:11
OK, I guess the question is whether we want to support that particular combination or not.

**Comment by jpcornil-git** [comment] 2024-03-07 16:35
Legacy HW could report HW_DEFAULT and new one HW_ESP32_V1 for ex.

Note that wrt API you may also want to add a message to report FW state to SW. Today SW/UI move back to configuration state as soon as the last line has been sent while FW has still to handle it, i.e. not really finished.

I saw that issue when I added a motor to a machine because last line was always missing.
On main, the issue is here (imageFinished should be set when FW transition to s_ready not when the last line has been sent)
https://github.com/AllYarnsAreBeautiful/ayab-desktop/blob/main/src/main/python/ayab/plugins/ayab_plugin/ayab_control.py#L806

**Comment by dl1com** [comment] 2024-03-07 16:47
Just my two cent:
In case adding RHS is too much of a hassle with the current hardware and we don't get a lean solution for it, we should leave it out. 


> The question also arises of how we know which version of the hardware is in use because right now the desktop has no way of knowing.
That's an info which is good to have in any case. Therefore we created https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/106 some time ago

**Comment by t0mpr1c3** [comment] 2024-03-07 16:54
If we can implement what JPC is suggesting we might not need changes to the API after all, so this does not necessarily need doing for v1.0, we can do it as feature release v1.1 or something.

**Comment by X-sam** [comment] 2024-03-30 20:52
Let's consider working with knit carriage sufficient for 1.0.0 and open additional tickets for additional functionality (and tag them `next` release).

**Closed** 2024-03-30 20:52 UTC
Labels: enhancement, feature
