### ISSUE TITLE
KH-920 + KG-93 + AYAB = won't working

### ISSUE THREAD

**Issue by Ilushock** [AllYarnsAreBeautiful/ayab-desktop#293] opened 2019-10-07 08:24 UTC
Hi! Image doesn't upload to the machine on the right turn. The shield doesn't "beep" at this moment.

Maybe I can use AYAB shield as BrotherLink cable to connect with DesignaKnit software? If it's possible, what I have to do?

**Comment by Adrienne200** [comment] 2019-10-08 15:29
AYAB does not work with the garter carriage (KG) yet. See
https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2
Is the patterning working for you otherwise?

There is no way that I know of to connect AYAB to DAK.

**Comment by Ilushock** [comment] 2019-10-08 18:18
>> Is the patterning working for you otherwise?
That's OK. But we want more-more-more )))

**Comment by chris007de** [comment] 2020-02-10 13:38
Duplicate of https://github.com/AllYarnsAreBeautiful/ayab-firmware/issues/2

**Closed by chris007de** 2020-02-10 13:38 UTC
Labels: duplicate
