### ISSUE TITLE
Double bed projects stop after knitting half of the rows

### ISSUE THREAD

**Issue by chris007de** [AllYarnsAreBeautiful/ayab-desktop#148] opened 2016-11-26 19:02 UTC
The using the doublebed/ribber mode, knitting stops after reaching half of total lines.

**Comment by chris007de** [comment] 2016-11-28 21:27
Get pattern image where this problem occurs from community to test the bugfix

**Comment by Adrienne200** [comment] 2016-12-15 05:22
This can be tested with any image to see it fail on v0.8, using Ribber with Infinite Repeat. Without Infinite Repeat it correctly knits to the end of the image.
Say your image is 20 rows tall. Set to 2-color, Infinite Repeat and Ribber. Air-knit as usual. As expected, it takes two passes per row. But when it gets to row 10, it goes back and starts again at row 1. 
Workaround is to make your image have two pattern repeats.

**Comment by Adrienne200** [comment] 2017-05-12 06:49
No, still the same.  
Any pattern file, infinite repeat and all standard settings except you're set to ribber instead of single. No need to actually have a ribber attached, easily seen by air-knitting on the main bed. Watch the row numbers, they are correct, each row gets two passes (with the needle selection of the second pass being the opposite of the first). For a 20-row image, after you have done 20 passes for 10 rows it goes back to the beginning, it should keep going until you've done 40 passes for 20 rows.

**Comment by chris007de** [comment] 2017-05-12 19:18
@Adrienne200 Please test

**Comment by Adrienne200** [comment] 2017-05-15 07:51
Not quite there yet. It now goes all the way to the top of the pattern but skips one carriage pass at the changeover back to the beginning.

0.9 RC3 on Win7-64
All standard settings except using Ribber.  2 color, starting at row 1.
You can see it by just air-knitting on the single bed, watching the rows carefully. Each row takes two passes, a dark-yarn pass with the pattern needles forwards at D position, and a light-yarn pass with the background needles forwards at D.
The attached file is 10 rows long, triangles from 1 to 10 stitches. Watch it select 1A 1B 2B 2A 3A 3B 4B 4A 5A 5B 6B 6A 7A 7B 8B 8A 9A 9B 
Next should be 10B 10A 1A 1B
But when it gets to row 10B and hops back to the beginning, it misses the 10A pass.
The green sample shows what happens when you knit it, think of it as dark triangles on light background. The second repeat has lost the pattern and is just stripes, which is what happens in DBJ if you get one pass out of sync. Then the third repeat has the two colors inverted, light on dark, because we are now 2 passes out of sync, the colors have reversed. Then more stripes, then the 4th repeat has the correct colors again. (For comparison, the red/beige is the same pattern in regular single-bed fair isle with infinite repeat)
![rownumbertest 60x10](https://cloud.githubusercontent.com/assets/24358225/26047418/fba93af6-3907-11e7-8822-d24e907e802c.png)
![dscf9170](https://cloud.githubusercontent.com/assets/24358225/26047433/0a7a1794-3908-11e7-8172-6f26b2202b9d.JPG)

**Comment by chris007de** [comment] 2017-05-16 20:03
@Adrienne200 Thanks for your detailed description, it helped a lot.
I fixed it, should be OK now :)

**Comment by Adrienne200** [comment] 2017-05-30 05:06
This looks to be fixed for the main case, starting at row 1.  I haven't knitted a DBJ sample yet, but observing the sequence as described above row 10A is now present, so it should work. 
However, see #167, crash when combining this DBJ sequence with starting at a row other than 1.

**Comment by Adrienne200** [comment] 2017-06-17 19:20
I knitted a sample on Windows starting at row 1, confirmed that that part is good now.
Starting at a row other than 1, see #167 
On Mac, (0.9 Rc4 dated June 10th) both cases are OK now.
So I think you can close this one now, leave #167 open until it is verified on Windows.

**Comment by Adrienne200** [comment] 2017-06-20 15:53
Oh, I spoke too soon, I hadn't tested all the cases. This fix is also needed for:
 - circular
 - 3 (or more) color DBJ (ribber)

**Comment by Adrienne200** [comment] 2017-06-21 05:32
I had added the comment about circular and 3-color only a few hours before you built RC5, so I wasn't expecting them to be fixed in RC5. Do you want to reopen this case, or should I write up a new one?

**Comment by chris007de** [comment] 2017-06-21 17:37
@Adrienne200  I'll just reopen it.
Just to get it right: In RC5, 2 color DBJ works and 3 (or more) and circular needs to be fixed?

**Comment by Adrienne200** [comment] 2017-06-23 04:21
That is correct. These two still fail, I think they're the last ones.
Circular, 2-color, infinite repeat.  (4 passes per row.)
Ribber, 3(or more) color, infinite repeat.  (6 passes per row)

**Comment by chris007de** [comment] 2017-06-23 19:47
@Adrienne200 should be fixed in RC6 (will be built in a few moments)

**Comment by Adrienne200** [comment] 2017-06-25 08:38
3-color and Circular now count to the end and repeat as expected. So I would close both this and #167. 
Except I found one more really obscure case where the infinite repeat sequence isn't right. :(

Attached odd-number-rows sample pattern, starting on an even row.
2 color, starting on row 2, inf repeat, ribber
should be
2A 2B 3B 3A 1A 1B 2B 2A 3A 3B 1B 1A 2A 2B 3B 3A 1A 1B
I'm getting
2A 2B 3B 3A 1A 1B*2A 2B 3B 3A 1A 1B*2A
* marks the places where it goes wrong.
Log is from Mac, behavior seen on both Mac and Windows.
From the log
0 0 reqLine: 0 imgRow: 1 indexToSend: 2 [0, 0, 1, 1, 0, 0, 0, 0,
0 1 reqLine: 1 imgRow: 1 indexToSend: 3 [1, 1, 0, 0, 1, 1, 1, 1,
0 2 reqLine: 2 imgRow: 2 indexToSend: 5 [1, 0, 0, 0, 1, 1, 1, 1,
0 3 reqLine: 3 imgRow: 2 indexToSend: 4 [0, 1, 1, 1, 0, 0, 0, 0,
0 4 reqLine: 4 imgRow: 0 indexToSend: 0 [0, 0, 0, 1, 0, 0, 0, 0,
0 5 reqLine: 5 imgRow: 0 indexToSend: 1 [1, 1, 1, 0, 1, 1, 1, 1,
 Line 7 should have come before line 6?
0 0 reqLine: 6 imgRow: 1 indexToSend: 2 [0, 0, 1, 1, 0, 0, 0, 0,
0 1 reqLine: 7 imgRow: 1 indexToSend: 3 [1, 1, 0, 0, 1, 1, 1, 1,
0 2 reqLine: 8 imgRow: 2 indexToSend: 5 [1, 0, 0, 0, 1, 1, 1, 1,

[Odd number rows start on even.txt](https://github.com/AllYarnsAreBeautiful/ayab-desktop/files/1100187/Odd.number.rows.start.on.even.txt)
![triangles 60x5](https://user-images.githubusercontent.com/24358225/27514651-ac2d7fb0-5945-11e7-80c1-7720ddee31fc.png)
![triangles 60x3](https://user-images.githubusercontent.com/24358225/27514652-ac3356ce-5945-11e7-9f6c-e4bb6e7f7a38.png)

**Comment by chris007de** [comment] 2017-06-28 16:45
@Adrienne200 Thanks for the feedback. I guess the current state of the "ABBA" rule is not transferred to the next run of the pattern in infinite mode, I'll have a look into it.

**Comment by Adrienne200** [comment] 2017-07-03 23:00
This looks good now, plus I went back over most of the other infinite repeat cases. I think we can close this now.

**Closed** 2017-07-04 00:15 UTC
Labels: bug, ready - please test
