### ISSUE TITLE
time lapse between the configure command and ability to knit

### ISSUE THREAD

**Issue by sandrina2** [AllYarnsAreBeautiful/ayab-desktop#296] opened 2020-01-26 13:22 UTC
I have been working with relatively small repeats, and am new to using version 9.5. My interface is an evil mad scientist kit on a Mac running Mojave 10.14.6. The time for configuring to complete is agonizingly, painfully slow and can take minutes. It is significantly slower than I can recall from when using the previous version. Once knitting, I have had no problem with my experiments which can be viewed and are documented on my blog, and so far have tested 3 color ribber options. Is there an explanation for the issue? It would lead a casual or new user to assume nothing is happening and the download is failing.

**Comment by chris007de** [comment] 2020-02-08 16:05
Hm, I am not aware of other users reporting such a behavior yet.
The logfiles might help to see where the communication fails/why it takes so long initially.
Could you please provide them?

**Comment by sandrina2** [comment] 2020-02-08 16:38
Hi Chris: 
thank you for taking time to get back to me regardings my question 
I heard back from Adrienne when I brought the issue up: “Regarding the slow startup, try clicking the Knit button anyway, even though it’s still gray. You’ll find that it’s actually ready for action within seconds of clicking Configure“. I have not had the opportunity to test that yet. I plan to try some more 3 color work and dbj soon, will share the result and confirm either way

so far I have really liked your multiple color separations, thank you and any remaining on the team for all the work on the update

Sandy
Alessandrina Costa
http://www.alessandrina.com/

**Comment by Adrienne200** [comment] 2020-03-29 16:33
I believe this is a duplicate of #282

**Comment by t0mpr1c3** [comment] 2020-05-30 04:45
I agree and recommend closing the issue

**Closed** 2020-05-31 14:09 UTC
Labels: bug
